import { User, Domain, DomainCategory, LeaderboardType, VerificationStatus } from "@/types";

export const mockDomains: Domain[] = [
  {
    id: "domain1",
    name: "example.com",
    expirationDate: new Date("2024-05-03"),
    description: "A generic example domain for testing purposes.",
    sellerId: "user1",
    sellerName: "John Doe",
    likes: 15,
    price: 99,
    isSponsored: false,
    isAdminPick: true,
    createdAt: new Date(),
    category: DomainCategory.Technology,
    tld: "com",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain2",
    name: "techinnovations.io",
    expirationDate: new Date("2024-05-15"),
    description: "Innovative tech solutions and resources.",
    sellerId: "user2",
    sellerName: "Alice Smith",
    likes: 28,
    price: 99,
    isSponsored: true,
    isAdminPick: false,
    createdAt: new Date(),
    category: DomainCategory.Technology,
    tld: "io",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain3",
    name: "healthfirst.org",
    expirationDate: new Date("2024-06-01"),
    description: "Your primary source for health-related information.",
    sellerId: "user3",
    sellerName: "Bob Johnson",
    likes: 8,
    price: 99,
    isSponsored: false,
    isAdminPick: false,
    createdAt: new Date(),
    category: DomainCategory.Health,
    tld: "org",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain4",
    name: "traveladventures.net",
    expirationDate: new Date("2024-06-10"),
    description: "Plan your next adventure with us!",
    sellerId: "user1",
    sellerName: "John Doe",
    likes: 35,
    price: 99,
    isSponsored: true,
    isAdminPick: true,
    createdAt: new Date(),
    category: DomainCategory.Travel,
    tld: "net",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain5",
    name: "businesssolutions.biz",
    expirationDate: new Date("2024-07-01"),
    description: "Providing top-notch business solutions for growth.",
    sellerId: "user2",
    sellerName: "Alice Smith",
    likes: 12,
    price: 99,
    isSponsored: false,
    isAdminPick: false,
    createdAt: new Date(),
    category: DomainCategory.Business,
    tld: "biz",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain6",
    name: "educationplus.info",
    expirationDate: new Date("2024-07-15"),
    description: "Enhancing education through innovative resources.",
    sellerId: "user3",
    sellerName: "Bob Johnson",
    likes: 20,
    price: 99,
    isSponsored: true,
    isAdminPick: false,
    createdAt: new Date(),
    category: DomainCategory.Education,
    tld: "info",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain7",
    name: "financeforward.co",
    expirationDate: new Date("2024-08-01"),
    description: "Moving finance forward with expert insights.",
    sellerId: "user1",
    sellerName: "John Doe",
    likes: 42,
    price: 99,
    isSponsored: false,
    isAdminPick: true,
    createdAt: new Date(),
    category: DomainCategory.Finance,
    tld: "co",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain8",
    name: "entertainmentnow.tv",
    expirationDate: new Date("2024-08-15"),
    description: "Your go-to source for the latest entertainment news.",
    sellerId: "user2",
    sellerName: "Alice Smith",
    likes: 10,
    price: 99,
    isSponsored: true,
    isAdminPick: false,
    createdAt: new Date(),
    category: DomainCategory.Entertainment,
    tld: "tv",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain9",
    name: "fashiontrends.store",
    expirationDate: new Date("2024-09-01"),
    description: "Stay ahead of the curve with the latest fashion trends.",
    sellerId: "user3",
    sellerName: "Bob Johnson",
    likes: 18,
    price: 99,
    isSponsored: false,
    isAdminPick: false,
    createdAt: new Date(),
    category: DomainCategory.Fashion,
    tld: "store",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain10",
    name: "foodlovers.blog",
    expirationDate: new Date("2024-09-15"),
    description: "A blog dedicated to food lovers everywhere.",
    sellerId: "user1",
    sellerName: "John Doe",
    likes: 25,
    price: 99,
    isSponsored: true,
    isAdminPick: true,
    createdAt: new Date(),
    category: DomainCategory.Food,
    tld: "blog",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain11",
    name: "ecommercemaster.store",
    expirationDate: new Date("2024-10-01"),
    description: "The perfect domain for your e-commerce business.",
    sellerId: "user2",
    sellerName: "Alice Smith",
    likes: 30,
    price: 249,
    isSponsored: true,
    isAdminPick: true,
    createdAt: new Date(),
    category: DomainCategory.Business,
    tld: "store",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain12",
    name: "healthandwellness.org",
    expirationDate: new Date("2024-10-15"),
    description: "Dedicated to health and wellness information.",
    sellerId: "user3",
    sellerName: "Bob Johnson",
    likes: 22,
    price: 199,
    isSponsored: false,
    isAdminPick: true,
    createdAt: new Date(),
    category: DomainCategory.Health,
    tld: "org",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain13",
    name: "techgadgets.shop",
    expirationDate: new Date("2024-11-01"),
    description: "The ultimate domain for tech gadgets e-commerce.",
    sellerId: "user1",
    sellerName: "John Doe",
    likes: 16,
    price: 179,
    isSponsored: true,
    isAdminPick: false,
    createdAt: new Date(),
    category: DomainCategory.Technology,
    tld: "shop",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain14",
    name: "educationportal.academy",
    expirationDate: new Date("2024-11-15"),
    description: "Your gateway to educational resources.",
    sellerId: "user2",
    sellerName: "Alice Smith",
    likes: 19,
    price: 299,
    isSponsored: false,
    isAdminPick: true,
    createdAt: new Date(),
    category: DomainCategory.Education,
    tld: "academy",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain15",
    name: "cryptoinvestors.finance",
    expirationDate: new Date("2024-12-01"),
    description: "Premium domain for cryptocurrency investment services.",
    sellerId: "user3",
    sellerName: "Bob Johnson",
    likes: 45,
    price: 499,
    isSponsored: true,
    isAdminPick: false,
    createdAt: new Date(),
    category: DomainCategory.Finance,
    tld: "finance",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain16",
    name: "travelexperiences.world",
    expirationDate: new Date("2024-12-15"),
    description: "Share your travel experiences with the world.",
    sellerId: "user1",
    sellerName: "John Doe",
    likes: 27,
    price: 349,
    isSponsored: true,
    isAdminPick: true,
    createdAt: new Date(),
    category: DomainCategory.Travel,
    tld: "world",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain17",
    name: "recipecollection.cooking",
    expirationDate: new Date("2025-01-01"),
    description: "The perfect domain for sharing cooking recipes.",
    sellerId: "user2",
    sellerName: "Alice Smith",
    likes: 33,
    price: 129,
    isSponsored: true,
    isAdminPick: false,
    createdAt: new Date(),
    category: DomainCategory.Food,
    tld: "cooking",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain18",
    name: "fashiontrends.boutique",
    expirationDate: new Date("2025-01-15"),
    description: "Keep up with the latest fashion trends.",
    sellerId: "user3",
    sellerName: "Bob Johnson",
    likes: 37,
    price: 279,
    isSponsored: false,
    isAdminPick: true,
    createdAt: new Date(),
    category: DomainCategory.Fashion,
    tld: "boutique",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain19",
    name: "sportsnetwork.tv",
    expirationDate: new Date("2025-02-01"),
    description: "The ultimate domain for sports coverage.",
    sellerId: "user1",
    sellerName: "John Doe",
    likes: 41,
    price: 399,
    isSponsored: true,
    isAdminPick: false,
    createdAt: new Date(),
    category: DomainCategory.Entertainment,
    tld: "tv",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain20",
    name: "artificialintelligence.tech",
    expirationDate: new Date("2025-02-15"),
    description: "Explore the world of artificial intelligence.",
    sellerId: "user2",
    sellerName: "Alice Smith",
    likes: 49,
    price: 599,
    isSponsored: false,
    isAdminPick: true,
    createdAt: new Date(),
    category: DomainCategory.Technology,
    tld: "tech",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain21",
    name: "greenplanet.eco",
    expirationDate: new Date("2025-03-01"),
    description: "Promote environmental consciousness with this domain.",
    sellerId: "user3",
    sellerName: "Bob Johnson",
    likes: 31,
    price: 189,
    isSponsored: true,
    isAdminPick: false,
    createdAt: new Date(),
    category: DomainCategory.Other,
    tld: "eco",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain22",
    name: "investmentstrategies.finance",
    expirationDate: new Date("2025-03-15"),
    description: "Share valuable investment strategies with your audience.",
    sellerId: "user1",
    sellerName: "John Doe",
    likes: 38,
    price: 449,
    isSponsored: false,
    isAdminPick: true,
    createdAt: new Date(),
    category: DomainCategory.Finance,
    tld: "finance",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain23",
    name: "onlinecourses.education",
    expirationDate: new Date("2025-04-01"),
    description: "The perfect domain for your online education platform.",
    sellerId: "user2",
    sellerName: "Alice Smith",
    likes: 26,
    price: 329,
    isSponsored: true,
    isAdminPick: true,
    createdAt: new Date(),
    category: DomainCategory.Education,
    tld: "education",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain24",
    name: "gamingnetwork.play",
    expirationDate: new Date("2025-04-15"),
    description: "Connect with the gaming community.",
    sellerId: "user3",
    sellerName: "Bob Johnson",
    likes: 44,
    price: 279,
    isSponsored: true,
    isAdminPick: false,
    createdAt: new Date(),
    category: DomainCategory.Entertainment,
    tld: "play",
    verificationStatus: VerificationStatus.VERIFIED,
  },
  {
    id: "domain25",
    name: "businesssolutions.company",
    expirationDate: new Date("2025-05-01"),
    description: "Professional domain for business solutions.",
    sellerId: "user1",
    sellerName: "John Doe",
    likes: 24,
    price: 399,
    isSponsored: false,
    isAdminPick: true,
    createdAt: new Date(),
    category: DomainCategory.Business,
    tld: "company",
    verificationStatus: VerificationStatus.VERIFIED,
  },
];

export const currentUser: User = {
  id: "user123",
  email: "test@example.com",
  name: "Test User",
  isAdmin: true,
  isVerified: true,
  createdAt: new Date(),
};

export const getLeaderboard = (type: LeaderboardType): Domain[] => {
  switch (type) {
    case LeaderboardType.MostLiked:
      return [...mockDomains].sort((a, b) => b.likes - a.likes);
    case LeaderboardType.AdminPicks:
      return mockDomains.filter(domain => domain.isAdminPick);
    case LeaderboardType.Sponsored:
      return mockDomains.filter(domain => domain.isSponsored);
    default:
      return mockDomains;
  }
};

export const getUniqueTLDs = (domains: Domain[]): string[] => {
  const tlds = domains.map(domain => domain.tld);
  return [...new Set(tlds)];
};

export const filterValidDomains = (domains: Domain[]): Domain[] => {
  return domains.filter(domain => 
    domain.name && 
    domain.expirationDate instanceof Date && 
    !isNaN(domain.expirationDate.getTime())
  );
};
