
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktldlcyglwcqjqkaxelk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0bGRsY3lnbHdjcWpxa2F4ZWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjQwODksImV4cCI6MjA1OTM0MDA4OX0.iKhzA5u3NG9KF9npS5rM0awpJ_Lt3QEaV6iCxekUHjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storage: localStorage
    }
  }
);
